### ISSUE TITLE
Incorrect status of mobile devices in case of multiple identical gadgets

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud#97] opened 2021-06-18 11:01 UTC
This problem occurs on Grid\STF level when there're several absolutely identical devices are situated in Mobile Cloud (actual for both Android and iOS). For instance, once one of this devices is physically removed from the Cloud, it's still reflected as available in both STF and Grid, while another device is displayed as disconnected.

**Comment by vdelendik** [comment] 2021-12-22 20:47
@rkatuzhanets, please explain identical? the same name or what?

**Comment by vdelendik** [comment] 2022-01-22 10:04
closing as can't reproduce.

**Closed by vdelendik** 2022-01-22 10:04 UTC
Labels: bug
